CREATE DATABASE SEMINAR_NDS
GO

USE SEMINAR_NDS
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- Check for the existence of tables
IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[BRAND_NDS]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
  DROP TABLE [dbo].[BRAND_NDS]
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[PRODUCT_NDS]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
  DROP TABLE [dbo].[PRODUCT_NDS]
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[CATEGORY_NDS]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
  DROP TABLE [dbo].[CATEGORY_NDS]
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DIRECTORY_NDS]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
  DROP TABLE [dbo].[DIRECTORY_NDS]
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[STORE_NDS]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
  DROP TABLE [dbo].[STORE_NDS]
GO

-- Create table
CREATE TABLE [dbo].[BRAND_NDS] (
	[BrandSK] INT IDENTITY(1,1) NOT NULL,
	[BrandNK] INT NOT NULL,
	[SourceID] INT NOT NULL,
	[BrandName] NVARCHAR(500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CreateDay] DATETIME NULL,
	[UpdateDay] DATETIME NULL
)
ON [PRIMARY]
GO

CREATE TABLE [dbo].[PRODUCT_NDS] (
	[ProductSK] INT IDENTITY(1,1) NOT NULL,
	[ProductNK] INT NOT NULL,
	[SourceID] INT NOT NULL,
	[BrandID] INT NOT NULL,
	[CategoryID] INT NOT NULL,
	[StoreID] INT NOT NULL,
	[DanhmucID] INT NOT NULL,
	[ProductName] NVARCHAR(500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ShortDescription] NVARCHAR(4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Price] INT NULL,
	[OriginalPrice] INT NULL,
	[Discount] INT NULL,
	[DiscountRate] INT NULL,
	[QuantitySold] INT NULL,
	[Rating] FLOAT NULL,
	[ReviewCount] INT NULL,
	[CreateDay] DATETIME NULL,
	[UpdateDay] DATETIME NULL
)
ON [PRIMARY]
GO

CREATE TABLE [dbo].[CATEGORY_NDS] (
	[CategorySK] INT IDENTITY(1,1) NOT NULL,
	[CategoryNK] INT NOT NULL,
	[SourceID] INT NOT NULL,
	[CategoryName] NVARCHAR(500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CreateDay] DATETIME NULL,
	[UpdateDay] DATETIME NULL
)
ON [PRIMARY]
GO

CREATE TABLE [dbo].[DIRECTORY_NDS] (
	[DirectorySK] INT IDENTITY(1,1) NOT NULL,
	[DirectoryNK] INT NOT NULL,
	[SourceID] INT NOT NULL,
	[DirectoryName] NVARCHAR(500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CreateDay] DATETIME NULL,
	[UpdateDay] DATETIME NULL
)
ON [PRIMARY]
GO

CREATE TABLE [dbo].[STORE_NDS] (
	[StoreSK] INT IDENTITY(1,1) NOT NULL,
	[StoreNK] INT NOT NULL,
	[SourceID] INT NOT NULL,
	[StoreName] NVARCHAR(500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[StoreOfficial] NVARCHAR(100) NULL,
	[StoreAVGRating] FLOAT NULL,
	[StoreReviewCount] INT NULL,
	[StoreTotalFollower] INT NULL,
	[CreateDay] DATETIME NULL,
	[UpdateDay] DATETIME NULL
)
ON [PRIMARY]
GO
-- Definition for indices :
ALTER TABLE [dbo].[BRAND_NDS]
ADD CONSTRAINT [PK_BRAND] 
PRIMARY KEY CLUSTERED ([BrandSK])
WITH (
  PAD_INDEX = OFF,
  IGNORE_DUP_KEY = OFF,
  STATISTICS_NORECOMPUTE = OFF,
  ALLOW_ROW_LOCKS = ON,
  ALLOW_PAGE_LOCKS = ON)
ON [PRIMARY]
GO

ALTER TABLE [dbo].[PRODUCT_NDS]
ADD CONSTRAINT [PK_PRODUCT] 
PRIMARY KEY CLUSTERED ([ProductSK])
WITH (
  PAD_INDEX = OFF,
  IGNORE_DUP_KEY = OFF,
  STATISTICS_NORECOMPUTE = OFF,
  ALLOW_ROW_LOCKS = ON,
  ALLOW_PAGE_LOCKS = ON)
ON [PRIMARY]
GO

ALTER TABLE [dbo].[CATEGORY_NDS]
ADD CONSTRAINT [PK_CATEGORY] 
PRIMARY KEY CLUSTERED ([CategorySK])
WITH (
  PAD_INDEX = OFF,
  IGNORE_DUP_KEY = OFF,
  STATISTICS_NORECOMPUTE = OFF,
  ALLOW_ROW_LOCKS = ON,
  ALLOW_PAGE_LOCKS = ON)
ON [PRIMARY]
GO


ALTER TABLE [dbo].[DIRECTORY_NDS]
ADD CONSTRAINT [PK_DIRECTORY] 
PRIMARY KEY CLUSTERED ([DirectorySK])
WITH (
  PAD_INDEX = OFF,
  IGNORE_DUP_KEY = OFF,
  STATISTICS_NORECOMPUTE = OFF,
  ALLOW_ROW_LOCKS = ON,
  ALLOW_PAGE_LOCKS = ON)
ON [PRIMARY]
GO

ALTER TABLE [dbo].[STORE_NDS]
ADD CONSTRAINT [PK_STORE] 
PRIMARY KEY CLUSTERED ([StoreSK])
WITH (
  PAD_INDEX = OFF,
  IGNORE_DUP_KEY = OFF,
  STATISTICS_NORECOMPUTE = OFF,
  ALLOW_ROW_LOCKS = ON,
  ALLOW_PAGE_LOCKS = ON)
ON [PRIMARY]
GO


select * from PRODUCT_NDS
select * from BRAND_NDS
select * from CATEGORY_NDS
select * from DIRECTORY_NDS
select * from STORE_NDS



truncate table PRODUCT_NDS
truncate table BRAND_NDS
truncate table CATEGORY_NDS
truncate table DIRECTORY_NDS
truncate table STORE_NDS
