CREATE DATABASE SEMINAR_SOURCE
GO

USE SEMINAR_SOURCE
GO

-- Check for the existence of tables
IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[BRAND_SOURCE]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
  DROP TABLE [dbo].[BRAND_SOURCE]
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[PRODUCT_SOURCE]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
  DROP TABLE [dbo].[PRODUCT_SOURCE]
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[CATEGORY_SOURCE]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
  DROP TABLE [dbo].[CATEGORY_SOURCE]
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DIRECTORY_SOURCE]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
  DROP TABLE [dbo].[DIRECTORY_SOURCE]
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[STORE_SOURCE]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
  DROP TABLE [dbo].[STORE_SOURCE]
GO


-- Create table
CREATE TABLE [dbo].[BRAND_SOURCE] (
  [BrandID] INT NOT NULL,
  [BrandName] NVARCHAR(500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
  [CreateDay] DATETIME NULL,
  [UpdateDay] DATETIME NULL
)
ON [PRIMARY]
GO

CREATE TABLE [dbo].[PRODUCT_SOURCE] (
  [ProductID] INT NOT NULL,
  [BrandID] INT NOT NULL,
  [CategoryID] INT NOT NULL,
  [StoreID] INT NOT NULL,
  [DanhmucID] INT NOT NULL,
  [ProductName] NVARCHAR(500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
  [ShortDescription] NVARCHAR(4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
  [Price] INT NULL,
  [OriginalPrice] INT NULL,
  [Discount] INT NULL,
  [DiscountRate] INT NULL,
  [QuantitySold] INT NULL,
  [Rating] FLOAT NULL,
  [ReviewCount] INT NULL,
  [CreateDay] DATETIME NULL,
  [UpdateDay] DATETIME NULL
)
ON [PRIMARY]
GO

CREATE TABLE [dbo].[CATEGORY_SOURCE] (
  [CategoryID] INT NOT NULL,
  [CategoryName] NVARCHAR(500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
  [CreateDay] DATETIME NULL,
  [UpdateDay] DATETIME NULL
)
ON [PRIMARY]
GO

CREATE TABLE [dbo].[DIRECTORY_SOURCE] (
  [DirectoryID] INT NOT NULL,
  [DirectoryName] NVARCHAR(500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
  [CreateDay] DATETIME NULL,
  [UpdateDay] DATETIME NULL
)
ON [PRIMARY]
GO

CREATE TABLE [dbo].[STORE_SOURCE] (
  [StoreID] INT NOT NULL,
  [StoreName] NVARCHAR(500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
  [StoreOfficial] NVARCHAR(100) NULL,
  [StoreAVGRating] FLOAT NULL,
  [StoreReviewCount] INT NULL,
  [StoreTotalFollower] INT NULL,
  [CreateDay] DATETIME NULL,
  [UpdateDay] DATETIME NULL
)
ON [PRIMARY]
GO
-- Definition for indices :
ALTER TABLE [dbo].[BRAND_SOURCE]
ADD CONSTRAINT [PK_BRAND] 
PRIMARY KEY CLUSTERED ([BrandID])
WITH (
  PAD_INDEX = OFF,
  IGNORE_DUP_KEY = OFF,
  STATISTICS_NORECOMPUTE = OFF,
  ALLOW_ROW_LOCKS = ON,
  ALLOW_PAGE_LOCKS = ON)
ON [PRIMARY]
GO

ALTER TABLE [dbo].[PRODUCT_SOURCE]
ADD CONSTRAINT [PK_PRODUCT] 
PRIMARY KEY CLUSTERED ([ProductID])
WITH (
  PAD_INDEX = OFF,
  IGNORE_DUP_KEY = OFF,
  STATISTICS_NORECOMPUTE = OFF,
  ALLOW_ROW_LOCKS = ON,
  ALLOW_PAGE_LOCKS = ON)
ON [PRIMARY]
GO

ALTER TABLE [dbo].[CATEGORY_SOURCE]
ADD CONSTRAINT [PK_CATEGORY] 
PRIMARY KEY CLUSTERED ([CategoryID])
WITH (
  PAD_INDEX = OFF,
  IGNORE_DUP_KEY = OFF,
  STATISTICS_NORECOMPUTE = OFF,
  ALLOW_ROW_LOCKS = ON,
  ALLOW_PAGE_LOCKS = ON)
ON [PRIMARY]
GO


ALTER TABLE [dbo].[DIRECTORY_SOURCE]
ADD CONSTRAINT [PK_DIRECTORY] 
PRIMARY KEY CLUSTERED ([DirectoryID])
WITH (
  PAD_INDEX = OFF,
  IGNORE_DUP_KEY = OFF,
  STATISTICS_NORECOMPUTE = OFF,
  ALLOW_ROW_LOCKS = ON,
  ALLOW_PAGE_LOCKS = ON)
ON [PRIMARY]
GO

ALTER TABLE [dbo].[STORE_SOURCE]
ADD CONSTRAINT [PK_STORE] 
PRIMARY KEY CLUSTERED ([StoreID])
WITH (
  PAD_INDEX = OFF,
  IGNORE_DUP_KEY = OFF,
  STATISTICS_NORECOMPUTE = OFF,
  ALLOW_ROW_LOCKS = ON,
  ALLOW_PAGE_LOCKS = ON)
ON [PRIMARY]
GO

-- Create trigger
--BRAND
CREATE TRIGGER UPDATE_BRANDSOURCE ON [dbo].[BRAND_SOURCE] AFTER UPDATE
AS 
BEGIN
	UPDATE [dbo].[BRAND_SOURCE]
	SET UpdateDay = GETDATE()
	WHERE BrandID IN (SELECT DISTINCT BrandID FROM inserted)
END
GO
CREATE TRIGGER INSERT_BRANDSOURCE ON [dbo].[BRAND_SOURCE] AFTER INSERT
AS
BEGIN
	UPDATE [dbo].[BRAND_SOURCE]
	SET CreateDay = GETDATE(), UpdateDay = GETDATE()
	WHERE BrandID IN (SELECT DISTINCT BrandID FROM inserted)
END
go
--PRODUCT
CREATE TRIGGER UPDATE_PRODUCTSOURCE ON [dbo].[PRODUCT_SOURCE] AFTER UPDATE
AS 
BEGIN
	UPDATE [dbo].[PRODUCT_SOURCE]
	SET UpdateDay = GETDATE()
	WHERE ProductID IN (SELECT DISTINCT ProductID FROM inserted)
END
GO
CREATE TRIGGER INSERT_PRODUCTSOURCE ON [dbo].[PRODUCT_SOURCE] AFTER INSERT
AS
BEGIN
	UPDATE [dbo].[PRODUCT_SOURCE]
	SET CreateDay = GETDATE(), UpdateDay = GETDATE()
	WHERE ProductID IN (SELECT DISTINCT ProductID FROM inserted)
END
go
--CATEGORY
CREATE TRIGGER UPDATE_CATEGORYSOURCE ON [dbo].[CATEGORY_SOURCE] AFTER UPDATE
AS 
BEGIN
	UPDATE [dbo].[CATEGORY_SOURCE]
	SET UpdateDay = GETDATE()
	WHERE CategoryID IN (SELECT DISTINCT CategoryID FROM inserted)
END
GO
CREATE TRIGGER INSERT_CATEGORYSOURCE ON [dbo].[CATEGORY_SOURCE] AFTER INSERT
AS
BEGIN
	UPDATE [dbo].[CATEGORY_SOURCE]
	SET CreateDay = GETDATE(), UpdateDay = GETDATE()
	WHERE CategoryID IN (SELECT DISTINCT CategoryID FROM inserted)
END
go
--DIRECTORY
CREATE TRIGGER UPDATE_DIRECTORYSOURCE ON [dbo].[DIRECTORY_SOURCE] AFTER UPDATE
AS 
BEGIN
	UPDATE [dbo].[DIRECTORY_SOURCE]
	SET UpdateDay = GETDATE()
	WHERE DirectoryID IN (SELECT DISTINCT DirectoryID FROM inserted)
END
GO
CREATE TRIGGER INSERT_DIRECTORYSOURCE ON [dbo].[DIRECTORY_SOURCE] AFTER INSERT
AS
BEGIN
	UPDATE [dbo].[DIRECTORY_SOURCE]
	SET CreateDay = GETDATE(), UpdateDay = GETDATE()
	WHERE DirectoryID IN (SELECT DISTINCT DirectoryID FROM inserted)
END
go
--STORE
CREATE TRIGGER UPDATE_STORESOURCE ON [dbo].[STORE_SOURCE] AFTER UPDATE
AS 
BEGIN
	UPDATE [dbo].[STORE_SOURCE]
	SET UpdateDay = GETDATE()
	WHERE StoreID IN (SELECT DISTINCT StoreID FROM inserted)
END
GO
CREATE TRIGGER INSERT_STORESOURCE ON [dbo].[STORE_SOURCE] AFTER INSERT
AS
BEGIN
	UPDATE [dbo].[STORE_SOURCE]
	SET CreateDay = GETDATE(), UpdateDay = GETDATE()
	WHERE StoreID IN (SELECT DISTINCT StoreID FROM inserted)
END
go

select * from PRODUCT_SOURCE
select * from BRAND_SOURCE
select * from CATEGORY_SOURCE
select * from DIRECTORY_SOURCE
select * from STORE_SOURCE

truncate table BRAND_SOURCE
truncate table PRODUCT_SOURCE
truncate table CATEGORY_SOURCE
truncate table DIRECTORY_SOURCE
truncate table STORE_SOURCE


